site_name: MidJourney Wiki
copyright: "Copyright &copy; 2022 AiHub.gg."
site_url: https://aihub.gg
repo_url: https://github.com/aihubgg/MidJourney-Wiki/
repo_name: aihubgg/MidJourney-Wiki
edit_uri: edit/main/docs/
nav:
        - Home: README.md
        - Discord FAQs:
                  - Overview: Discord-FAQs/overview.md
                  - Other Resources: Discord-FAQs/OtherResources.md
                  - Promt-Craft FAQs:
                                - Overview: Discord-FAQs/Prompt-Craft-FAQ/overview.md
                                - clarinet: Discord-FAQs/Prompt-Craft-FAQ/clarinet.md
                                - Tally: Discord-FAQs/Prompt-Craft-FAQ/Tally.md
                                - AfterEarth: Discord-FAQs/Prompt-Craft-FAQ/AfterEarth.md
                                - shambibble: Discord-FAQs/Prompt-Craft-FAQ/shambibble.md
                                - TwinGodhead: Discord-FAQs/Prompt-Craft-FAQ/TwinGodhead.md
                                - 2hanssen4u: Discord-FAQs/Prompt-Craft-FAQ/2hanssen4u.md
                                - Saukko: Discord-FAQs/Prompt-Craft-FAQ/Saukko.md
                                - JeremyCurious: Discord-FAQs/Prompt-Craft-FAQ/JermeyCurious.md
                                - Other Resources: Discord-FAQs/Prompt-Craft-FAQ/OtherResources.md
        - External Resources:
                  - Styles and Keywords Reference: MidjourneySAR.md
theme:
        name: material
        custom_dir: overrides
        highlightjs: true
        hljs_languages:
                - yaml
        icon:
                repo: fontawesome/brands/github
        navigation_depth: 6
        titles_only: false
        favicon: /static/midjourney.png
        logo: /static/midjourney.png
        features:
                - navigation.instant
        palette:
                - media: "(prefers-color-scheme: light)"
                  scheme: default
                  toggle:
                          icon: material/weather-sunny
                          name: Switch to dark mode
                - media: "(prefers-color-scheme: dark)"
                  scheme: slate
                  primary: blue
                  toggle:
                          icon: material/weather-night
                          name: Switch to light mode
markdown_extensions:
        - toc:
                  permalink: "#"
                  toc_depth: "1-2"
        - smarty
        - admonition
        - footnotes
        - codehilite
        - pymdownx.arithmatex
        - pymdownx.betterem:
                  smart_enable: all
        - pymdownx.caret
        - pymdownx.critic
        - pymdownx.details
        - pymdownx.emoji:
                  emoji_generator: !!python/name:pymdownx.emoji.to_svg
        - pymdownx.inlinehilite
        - pymdownx.magiclink
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.superfences
        - pymdownx.tabbed:
                  alternate_style: true
        - pymdownx.tasklist:
                  custom_checkbox: true
        - pymdownx.tilde
        - fontawesome_markdown
        - tables
        - attr_list
        - md_in_html
plugins:
  - search # necessary for search to work
  - git-revision-date-localized:
      type: datetime
  - git-committers:
      repository: squidfunk/mkdocs-material
      token: !ENV GH_TOKEN
  - social
extra:
  manifest: "static/site.webmanifest"
  analytics:
        provider: google
        property: G-6D0LKC374E
