site_name: MidJourney Wiki
copyright: "Copyright &copy; 2022 AiHub.gg."
site_url: https://mj.aihub.gg
repo_url: https://github.com/aihubgg/MidJourney-Wiki/
repo_name: aihubgg/MidJourney-Wiki
edit_uri: edit/main/docs/
nav:
        - Home: README.md
        - Discord FAQs:
                  - Overview: Discord-FAQs/overview.md
                  - Other Resources: Discord-FAQs/OtherResources.md
                  - Promt-Craft FAQs:
                                - Overview: Discord-FAQs/Prompt-Craft-FAQ/overview.md
                                - clarinet: Discord-FAQs/Prompt-Craft-FAQ/clarinet.md
                                - Tally: Discord-FAQs/Prompt-Craft-FAQ/Tally.md
                                - AfterEarth: Discord-FAQs/Prompt-Craft-FAQ/AfterEarth.md
                                - shambibble: Discord-FAQs/Prompt-Craft-FAQ/shambibble.md
                                - TwinGodhead: Discord-FAQs/Prompt-Craft-FAQ/TwinGodhead.md
                                - 2hanssen4u: Discord-FAQs/Prompt-Craft-FAQ/2hanssen4u.md
                                - Saukko: Discord-FAQs/Prompt-Craft-FAQ/Saukko.md
                                - JeremyCurious: Discord-FAQs/Prompt-Craft-FAQ/JermeyCurious.md
                                - Other Resources: Discord-FAQs/Prompt-Craft-FAQ/OtherResources.md
        - External Resources:
                  - Overview: External-Resources/Overview.md
                  - Styles and Keywords Reference: External-Resources/MidjourneySAR.md 
                  - promptoMANIA: 
                  - The Ai Art: External-Resources/the-ai-art.md
                  - Prompt Builders: 
                                - promptoMANIA: External-Resources/Prompt-Builders/promptoMANIA.md
                  - Art Mechanicum:
                                - Overview: External-Resources/Art-Mechanicum/ArtMechanicum.md
                                - Guides:
                                       - Scaling Images Up: External-Resources/Art-Mechanicum/Guides/ScalingImagesUp.md

theme:
        name: material
        custom_dir: overrides
        highlightjs: true
        hljs_languages:
                - yaml
        icon:
                repo: fontawesome/brands/github
        titles_only: false
        favicon: static/midjourney.png
        logo: static/midjourney.png
        features:
                - navigation.instant
                - navigation.prune
                - announce.dismiss
        palette:
                - media: "(prefers-color-scheme: light)"
                  scheme: default
                  primary: blue
                  toggle:
                          icon: material/weather-sunny
                          name: Switch to dark mode
                - media: "(prefers-color-scheme: dark)"
                  scheme: slate
                  primary: blue
                  toggle:
                          icon: material/weather-night
                          name: Switch to light mode
markdown_extensions:
        - toc:
                  permalink: "#"
                  toc_depth: "1-2"
        - smarty
        - admonition
        - footnotes
        - codehilite
        - pymdownx.arithmatex
        - pymdownx.betterem:
                  smart_enable: all
        - pymdownx.caret
        - pymdownx.critic
        - pymdownx.details
        - pymdownx.emoji:
                  emoji_generator: !!python/name:pymdownx.emoji.to_svg
                  emoji_index: !!python/name:materialx.emoji.twemoji
        - pymdownx.inlinehilite
        - pymdownx.magiclink
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.superfences
        - pymdownx.tabbed:
                  alternate_style: true
        - pymdownx.tasklist:
                  custom_checkbox: true
        - pymdownx.tilde
        - fontawesome_markdown
        - tables
        - attr_list
        - md_in_html
plugins:
  - search # necessary for search to work
  - git-revision-date-localized:
      type: datetime
  - git-committers:
      repository: aihubgg/MidJourney-Wiki
      token: !ENV GH_TOKEN
  - social
  - external-markdown
  - meta
  - tags
extra:
  analytics:
        provider: google
        property: G-6D0LKC374E
  social:
                - icon: fontawesome/brands/discord
                  link: "https://discord.gg/CN4xnR9sEa"
