site_name: MidJourney Wiki
copyright: "Copyright &copy; 2021 AiHub.gg."
site_url: https://aihub.gg
repo_url: https://github.com/aihubgg/MidJourney-Wiki
repo_name: aihubgg/MidJourney-Wiki
nav:
        - Home: README.md
        - Discord FAQs:
                  - Overview: Discord-FAQs/overview.md
                  - clarinet: Discord-FAQs/clarinet.md
                  - AfterEarth: Discord-FAQs/AfterEarth.md
                  - Tally: Discord-FAQs/Tally.md
                  - Danger Awesome: Discord-FAQs/DangerAwesome.md
                  - Dr3am L0g1c: Discord-FAQs/Dr3amL0g1c.md
                  - shambibble: Discord-FAQs/shambibble.md
                  - TwinGodhead: Discord-FAQs/TwinGodhead.md
                  - 2hanssen4u: Discord-FAQs/2hanssen4u.md
                  - Saukko: Discord-FAQs/Saukko.md
                  - JeremyCurious: Discord-FAQs/JermeyCurious.md
theme:
        name: material
        highlightjs: true
        hljs_languages:
                - yaml
        icon:
                repo: fontawesome/brands/github
        navigation_depth: 6
        titles_only: false
        favicon: /static/midjourney.png
        logo: /static/midjourney.png
        features:
                - navigation.instant
        palette:
                - media: "(prefers-color-scheme: light)"
                  scheme: default
                  toggle:
                          icon: material/weather-sunny
                          name: Switch to dark mode
                - media: "(prefers-color-scheme: dark)"
                  scheme: slate
                  primary: blue
                  toggle:
                          icon: material/weather-night
                          name: Switch to light mode
markdown_extensions:
        - toc:
                  permalink: "#"
                  toc_depth: "1-2"
        - smarty
        - admonition
        - footnotes
        - codehilite
        - pymdownx.arithmatex
        - pymdownx.betterem:
                  smart_enable: all
        - pymdownx.caret
        - pymdownx.critic
        - pymdownx.details
        - pymdownx.emoji:
                  emoji_generator: !!python/name:pymdownx.emoji.to_svg
        - pymdownx.inlinehilite
        - pymdownx.magiclink
        - pymdownx.mark
        - pymdownx.smartsymbols
        - pymdownx.superfences
        - pymdownx.tabbed:
                  alternate_style: true
        - pymdownx.tasklist:
                  custom_checkbox: true
        - pymdownx.tilde
        - fontawesome_markdown
        - tables
        - markdown-grid-table
extra:
        manifest: "static/site.webmanifest"